### ISSUE TITLE
ConfigParser  raises exception for pyproject.toml if file has duplicate block.

### ISSUE THREAD

**Issue by b0g3r** [3YOURMIND/django-migration-linter#144]
I use poetry with a few additional pypi sources, so my pyproject.toml contains something like this:

```toml
[[tool.poetry.source]]
name = "custom-pypi-1"
url = "https://custom-pypi-1/simple/"

[[tool.poetry.source]]
name = "custom-pypi-2"
url = "https://custom-pypi-2/simple/"
```

Unfortunately with upgrading to the last version I got configparser exception
```
configparser.DuplicateSectionError: While reading from 'pyproject.toml' [line 64]: section '[tool.poetry.source' already exists
```

AFAIK, toml isn't backward compatible with ini, so the configparser cannot parse all features and can raise exceptions in such cases.
